# sys_pins.xdc -- top-level physical pin / clock constraints for `sys_top`.
#
# CONVERGED 2026-09-14.  The previous content of this file was the complete pin
# constraint set of a DIFFERENT, larger board design (PL DDR4 + GTYE4 optical
# channels + an `aad01s040g_module_inst` + an RF microwave switch matrix +
# `test_io_*`).  It had been imported from
#     ../../zu_rfsoc_test/zu_rfsoc_test.srcs/constrs_1/new/sys_pins.xdc
# and never trimmed.  It carried 119 active constraints that referenced 114
# ports, while the current `sys_top` exposes only 22 ports -- so 108 of the
# constrained ports did not exist.  Those constraints produced 103 violation
# messages per design stage (`Common 17-55`, `Vivado 12-4739`, `Common 17-162`).
#
# Only constraints that resolve against real `sys_top` ports are kept below.
# Nothing new was added; this file is now a strict subset of the old one.
#
# The untouched original is archived next to this file as
#     sys_pins.xdc.legacy-full.bak
# SHA-256 (original) = B74F224EA3FB29C69AE0CAD13D27A38E2A5F0AB152805045673C27E095975A41
# (not registered in the Vivado project; it is an archive, not a constraint set)
#
# ---------------------------------------------------------------------------
# Removed, with the concrete reason each one could not resolve:
#
#   ddr4_*                      PL DDR4 is not exported by design_1: the
#                               Zynq UltraScale+ PS DDR4 is internal to the PS
#                               and no PL DDR4 interface exists in this design.
#                               Covered ddr4_sys_clk_p/n, ddr4_act_n,
#                               ddr4_reset_n, ddr4_bg, ddr4_odt, ddr4_cs_n,
#                               ddr4_cke, ddr4_ba, ddr4_ck_c/t, ddr4_dm_n,
#                               ddr4_adr, ddr4_dq, ddr4_dqs_c/t.
#   single_bit_adc_*            No such ADC module in this design:
#                               rst/sclk/csn/miso/mosi/sync/refclk_p/rx_p[0..3].
#   rf_mw_*                     RF microwave switch matrix does not exist:
#                               sync/rx_det/r0_t0_sw/t1_sw/freq_code[0..15].
#   test_io_pl / test_io_ps     Test I/O is commented out of `sys_top`; the pin
#                               lines were already commented, and the port does
#                               not exist.
#   set_property LOC GTYE4_*    Targets
#   [get_cells aad01s040g_module_inst/.../GTYE4_CHANNEL_PRIM_INST] -- module
#                               absent from this design.
#   connect_debug_port          `dbg_hub/clk [get_nets clk_out2_100M]` could not
#                               resolve the net name at top level
#                               (`Common 17-162`).  The debug hub clock is
#                               defined by the generated BD/debug-core XDC.
#
# Clocks are NOT lost by this trim:
#   * `sys_clk_p` (200 MHz differential) is created by the block-design
#     constraint set (`design_1_ooc.xdc`:
#     `create_clock -name sys_clk_p -period 5 [get_ports sys_clk_p]`).
#   * `clk_adc0` (3.333 ns), `clk_200M` (5.000 ns) and `clk_dac0` (3.333 ns)
#     are generated by the BD `clk_wiz` output pins and are independently
#     gated by `build_adda_bitstream_xsa.tcl` (`task7_require_clock`).
# ---------------------------------------------------------------------------

# 200 MHz differential system clock from the board oscillator.
create_clock -period 5.000 [get_ports sys_clk_p]

# HMC7044 clock-chip SPI (slow configuration interface).
create_clock -period 100.000 -name hmc7044_sclk [get_ports hmc7044_sclk]

# --- Board pin assignment -----------------------------------------------------
set_property -dict {PACKAGE_PIN E11 IOSTANDARD DIFF_HSTL_I_18} [get_ports sys_clk_p]
set_property -dict {PACKAGE_PIN E10 IOSTANDARD DIFF_HSTL_I_18} [get_ports pl_sysref_p]

# HMC7044 clock generator control (4-wire SPI, `hmc7044_sdio` is bidirectional).
set_property -dict {PACKAGE_PIN J12 IOSTANDARD LVCMOS33} [get_ports hmc7044_rst]
set_property -dict {PACKAGE_PIN H9  IOSTANDARD LVCMOS33} [get_ports hmc7044_sclk]
set_property -dict {PACKAGE_PIN H10 IOSTANDARD LVCMOS33} [get_ports hmc7044_csn]
set_property -dict {PACKAGE_PIN K11 IOSTANDARD LVCMOS33} [get_ports hmc7044_sdio]

# The unused QSPI register's IOB override is in unused_qspi_iob.xdc.
# Read that file only for implementation, with PROCESSING_ORDER=LATE.
